DRIVE_STICK = 0
CUBE_STICK = 1

# LED relays.
GREEN_LED = 0
YELLOW_LED = 1
RED_LED = 2

# Sensors.
PHOTOSENSOR = 8
LEFT_ENC_ONE = 2
LEFT_ENC_TWO = 3
RIGHT_ENC_ONE = 0
RIGHT_ENC_TWO = 1
ELEV_LIMIT_ONE = 6
ELEV_LIMIT_TWO = 7
ELEVATOR_ENC_ONE = 4
ELEVATOR_ENC_TWO = 5

# MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS MOTORS
# Drivetrain motors.
LEFT_DRIVE1 = 2
LEFT_DRIVE2 = 3
RIGHT_DRIVE1 = 0
RIGHT_DRIVE2 = 1

# Intake Motors
LEFT_INTAKE = 6
RIGHT_INTAKE = 7
INTAKE_PIVOT = 0

# Elevator Motors
ELEV_ONE = 4
ELEV_TWO = 5

# SOLENOIDS SOLENOIDS SOLENOIDS SOLENOIDS SOLENOIDS SOLENOIDS SOLENOIDS SOLENOIDS SOLENOIDS SOLENOIDS SOLENOIDS
# Intake Solenoids
OPEN_INTAKE = 0
CLOSE_INTAKE = 1
