DRIVE_WHEEL_SIZE = 4.0

DEFAULT_AUTO_DISTANCE = 0.0

DEFAULT = "Default"
LEFT_POS = "Left"
RIGHT_POS = "Right"
CENTER_POS = "Center"
AUTO_RUN = "Auto Run"

DRIVE_MAX_ANGLE = 4.0
DRIVE_ZERO_SPEED = 0.0
DRIVE_TURNING_SPEED = 0.80
DRIVE_TURNING_SPEED2 = 0.5
DRIVE_DRIVING_SPEED = 0.60
INTAKE_ZERO_SPEED = 0.0
INTAKE_VOMIT_SPEED = -0.4
INTAKE_PICKUP_SPEED = 0.5

OPEN_INTAKE = True
CLOSE_INTAKE = False


DRIVE_ENC_UNITS = 256.0 * 42.0 / 36.0
ELEVATOR_ENC_UNITS = 256.0